import { useAppSelector } from '../../app/hooks';
import { A4Paper } from '../../components/screen/A4Paper';
import { Paginator } from '../../components/shared/Paginator';
import { BoardGrid } from '../../components/screen/BoardGrid';
import { BoardHeader } from '../../components/screen/BoardHeader';
import { BoardFooter } from '../../components/screen/BoardFooter';
import { DEFAULT_HEADER_TEXT } from '../../constants/appText';

function MainView() {
  const chosenKanjis = useAppSelector((state) => state.kanji.chosenKanjis);
  const currentMode = useAppSelector((state) => state.worksheet.currentMode);
  const currentPage = useAppSelector((state) => state.worksheet.currentPage);
  const worksheet = useAppSelector((state) => state.worksheet);

  // Calculate cards per page for board mode
  const calculateCardsPerPage = () => {
    if (currentMode !== 'board') return 20; // Placeholder for sheet mode
    
    // Match BoardGrid calculations exactly
    const availableWidth = 698;
    let availableHeight = 1027;
    
    // Subtract header height if visible (50px)
    if (worksheet.boardShowHeader) {
      availableHeight -= 50;
    }
    
    // Subtract footer height if visible (40px)
    if (worksheet.boardShowFooter) {
      availableHeight -= 40;
    }
    
    // Account for container padding (pt-1 = 4px)
    availableHeight -= 4;
    
    const gap = 2;
    
    const cellSize = Math.floor((availableWidth - (worksheet.boardColumnCount - 1) * gap) / worksheet.boardColumnCount);
    
    // Calculate rows with proper gap handling (no gap after last row)
    const rowCount = Math.floor((availableHeight + gap) / (cellSize + gap));
    return rowCount * worksheet.boardColumnCount;
  };

  const cardsPerPage = calculateCardsPerPage();
  const totalPages = Math.max(1, Math.ceil(chosenKanjis.length / cardsPerPage));
  const startIndex = (currentPage - 1) * cardsPerPage;

  return (
    <div
      data-testid="main-view"
      className="bg-gray-700 rounded-lg p-4 flex flex-col h-full overflow-hidden gap-3"
    >
      {/* A4 Paper Container */}
      <div className="flex-1 min-h-0">
        <A4Paper>
          {currentMode === 'board' ? (
            <div className="flex flex-col h-full" style={{ overflow: 'visible' }}>
              <BoardHeader visible={worksheet.boardShowHeader} />
              
              <div className="flex-1 overflow-hidden pt-1">
                {chosenKanjis.length === 0 ? (
                  <div className="flex items-center justify-center h-full text-gray-500 text-center px-8">
                    Select kanji from the Input Panel to generate worksheet
                  </div>
                ) : (
                  <BoardGrid
                    kanjis={chosenKanjis}
                    startIndex={startIndex}
                    columnCount={worksheet.boardColumnCount}
                    emptyCellsMode={worksheet.boardEmptyCellsMode}
                    grayscaleMode={worksheet.grayscaleMode}
                    showHeader={worksheet.boardShowHeader}
                    showFooter={worksheet.boardShowFooter}
                  />
                )}
              </div>
              
              <BoardFooter 
                currentPage={currentPage} 
                totalPages={totalPages}
                visible={worksheet.boardShowFooter} 
              />
            </div>
          ) : (
            // Sheet mode placeholder
            <div className="p-8">
              <div className="p-8 border-b border-gray-400 flex justify-between items-center text-sm">
                <span>{DEFAULT_HEADER_TEXT}</span>
                <span>Page {currentPage}</span>
                <span>Name: _____________</span>
              </div>

              <div className="p-8 pb-20">
                {chosenKanjis.length === 0 ? (
                  <div className="text-center text-gray-500 py-20">
                    Select kanji from the Input Panel to generate worksheet
                  </div>
                ) : (
                  <div className="text-center">
                    Worksheet for {chosenKanjis.length} kanji in sheet mode will render here
                  </div>
                )}
              </div>

              <div className="absolute bottom-0 left-0 right-0 p-8 border-t border-gray-400 text-xs text-gray-600">
                <span>Generated by Kanji Worksheet Generator</span>
              </div>
            </div>
          )}
        </A4Paper>
      </div>

      {/* Paginator */}
      <div className="flex justify-center flex-shrink-0">
        <Paginator
          currentPage={currentPage}
          totalPages={totalPages}
        />
      </div>
    </div>
  );
}

export default MainView;
