export interface HeaderProps {
  mode: 'sheet' | 'board';
  className?: string;
}

export function Header({ mode, className = '' }: HeaderProps) {
  if (mode === 'board') {
    return (
      <div 
        className={`px-8 py-4 border-b border-gray-400 text-center text-sm font-medium ${className}`}
        data-testid="board-header"
      >
        Kanji board - generated by Fong Thai
      </div>
    );
  }

  // Sheet mode header
  return (
    <div 
      className={`px-8 py-4 border-b border-gray-400 flex justify-between items-center text-sm ${className}`}
      data-testid="sheet-header"
    >
      <span>Kanji Practice Worksheet</span>
      <span>Name: _____________</span>
    </div>
  );
}

export interface FooterProps {
  mode: 'sheet' | 'board';
  currentPage?: number;
  totalPages?: number;
  className?: string;
}

export function Footer({ mode, currentPage, totalPages, className = '' }: FooterProps) {
  if (mode === 'board') {
    return (
      <div 
        className={`px-8 py-4 border-t border-gray-400 text-xs text-gray-600 text-center ${className}`}
        data-testid="board-footer"
      >
        {currentPage && totalPages ? `Page ${currentPage} of ${totalPages}` : 'Page 1 of 1'}
      </div>
    );
  }

  // Sheet mode footer
  return (
    <div 
      className={`px-8 py-4 border-t border-gray-400 text-xs text-gray-600 ${className}`}
      data-testid="sheet-footer"
    >
      Generated by Kanji Worksheet Generator
    </div>
  );
}
