interface BoardFooterProps {
  currentPage: number;
  totalPages: number;
  visible: boolean;
}

export function BoardFooter({ currentPage, totalPages, visible }: BoardFooterProps) {
  if (!visible) return null;
  
  return (
    <div 
      style={{ 
        height: '40px',
        display: 'flex',
        flexDirection: 'column',
        background: 'white',
      }}
    >
      {/* Gap above line */}
      <div style={{ height: '2px', background: 'white' }}></div>
      
      {/* Horizontal Line */}
      <div style={{ height: '2px', background: '#9ca3af' }}></div>
      
      {/* Footer Content */}
      <div 
        className="px-4 bg-white flex justify-between items-center"
        style={{ height: '36px' }}
      >
        {/* Left: Generation text */}
        <p className="text-sm text-gray-600">
          Generated by Fong Thai Kanji Tool
        </p>
        
        {/* Right: Page numbers */}
        <p className="text-sm text-gray-600">
          Page {currentPage} of {totalPages}
        </p>
      </div>
    </div>
  );
}
