/**
 * Application Text Constants
 * 
 * Centralized text constants used throughout the application
 * for headers, footers, and other UI text.
 */

// Default header text
export const DEFAULT_HEADER_TEXT = 'Fong Thai Kanji App';

// Footer text
export const FOOTER_TEXT = 'Generated by Fong Thai Kanji App';

// Footer text with timestamp
export const getFooterText = (t?: (key: string, params?: any) => string): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.toLocaleString('en-US', { month: 'short' });
  const day = String(now.getDate()).padStart(2, '0');
  const hours = String(now.getHours()).padStart(2, '0');
  const minutes = String(now.getMinutes()).padStart(2, '0');
  
  if (t) {
    return t('labels.generated_by', { date: `${year}-${month}-${day}`, time: `${hours}:${minutes}` });
  }
  
  return `Generated by Fong Thai Kanji App on ${year}-${month}-${day} at ${hours}:${minutes}`;
};

// App name
export const APP_NAME = 'Fong Thai Kanji App';
