/**
 * Application Text Constants
 * 
 * Centralized text constants used throughout the application
 * for headers, footers, and other UI text.
 */

// Default header text
export const DEFAULT_HEADER_TEXT = 'Fong Thai Kanji App';

// Footer text
export const FOOTER_TEXT = 'Generated by Fong Thai Kanji App';

// App name
export const APP_NAME = 'Fong Thai Kanji App';
